Introduce Timed Intervals for MQTT Messages
tspopp/AquaMQTT pull request #37
Opened 2024-10-04 20:30 UTC by redahb

This PR introduces timers for all MQTT topics (Energy, Main, HMI, and Stats), ensuring data is sent only at the configured intervals rather than immediately after a value change (e.g., water temperature).

Full updates and Error updates remain unaffected: Full updates are already configurable, and Error messages should still be relayed ASAP for critical notifications.

I initiated this change because my Atlantic Explorer V4 was sending temperature values approximately every 0.5 seconds, which overwhelmed the Home Assistant recorder. Since AquaMQTT controls heat pumps, real-time temperature data isn’t essential. Configurable intervals, such as 1 or 5 minutes, provide a more practical solution.

2024-10-06 19:19 UTC, tspopp requested changes
Hey @redahb, thanks for the contribution! There are similarities to the request in https://github.com/tspopp/AquaMQTT/issues/19. It seems the amount of data published is really an issue. 

The changes are quite good, but I am missing a switch in the configuration to keep the original behavior, for example `constexpr bool MQTT_PUBLISH_IMMEDIATELY_ON_CHANGE = true` and then adapt the check a litte, for example:

```
if (((notify & 1 << 8) != 0) && MQTT_PUBLISH_IMMEDIATELY_ON_CHANGE || hmiUpdate || fullUpdate)
```

Another way of solving this issue is adding additional filters before publishing as requested in https://github.com/tspopp/AquaMQTT/issues/19.

If you add the suggested additional configuration option to keep the original behavior, I'd love to merge this. Great work! Thanks :)

2024-10-28 15:38 UTC, henrykuijpers commented
@tspopp I notice the same thing with my boiler (with the latest main branch): 
<img width="337" alt="image" src="https://github.com/user-attachments/assets/5147c03a-d65f-4120-a093-09db55a46bdd">

It seems it publishes a new time update every second! 
It also seems that the amount of messages that are going through the HMI is quite large, even though it seems the boiler isn't doing so much. So next to that time update every second, there is also an update every few seconds when a new message was processed.

2024-10-28 16:01 UTC, tspopp commented
I will increase the default configuration interval for the stats topic in the next version to a higher value. This will reduce the updates for the debug message values.

For the time value I would propose to remove the seconds from the MQTT payload. So this would lead to an update every minute.

Does this sound feasible? :)

2024-10-28 16:26 UTC, henrykuijpers commented
Yes, that sounds good already! That saves 59 updates per minute. :P Maybe even hourly would be useful. 

It would also be nice to be able to just turn this off, as it would not be very useful for a lot of users. If you can turn it on via Mqtt, then you can use it temporarily for debugging.

2024-10-28 16:28 UTC, henrykuijpers commented
For the HMI & main, messages sent and handled, it would also be good to find a good threshold, as it currently spams a lot. Normally you would be interested in the functioning of the controller. Maybe a messages handled / sent per minute or something could be useful? 

I'm definitely not interested in receiving that +1 each and everytime, for 4 different stats. 

I just want to know that my controller is working correctly.

2024-10-28 16:56 UTC, tspopp commented
Well, you might also disable MQTT discovery and write your own configuration file in home assistant to filter the not wanted attributes. I am willing to do a few optimizations here and there, but since this is a non profit and free open source project, I put my free time where it makes sense to me.

You may always come up with a PR, but I might propose changes to not break existing functionality like within this PR, which I do happily merge as soon as @redahb pushes changes.

Sometimes I feel like, I sold you guys a product. But this is open source, happy to get your comments but at some point just use it as it is 🤷‍♂️

2024-10-28 17:54 UTC, tspopp commented
No worries, maybe some misinterpretation due to translation. But yeah, this is not *a product*. 

The only values which change frequently are the temperature values and they should be silenced using kalman filters. So rule of thumb, if there is a change, it is a change you also want to see within homeassistant. If you do filtering time-based, like one value every 5 minutes, you will lose resolution and there won't be any neat graphs in home assistant. Therefore, I suggested going with kalman filters. You will get more mqtt messages when the heat-pump is heating up (since the value is actually changing a lot!), and less mqtt messages if it is idle (less change). If somebody takes water out of your heat-pump, there will be more messages. But none of the message is sent twice for the same value. For me, this solution is perfect and I don't really see the need for something to be added.

Regarding debugging stats, we can disable them entirely if the current stats timer configuration is not enough. The reason I have this is if people using AquaMQTT with newer heat pumps or if there are connectivity issues due to hardware issues. I always expected CRC fails or even dropped bytes if there is something wrong. If somebody has troubles in first place, I can always ask for these metrics, in order to get a direction to debug. 

In your case, everything already works fine which is great. So if you're not interested in these values which I understand, we can just add a switch to disable them entirely. 

Time and Date is also something which should be disabled. If you're playing around with RTC or using another NTP time server than default, it is of interest which time AquaMQTT is actually using. But since there are currently no known bugs I guess we can also disable them by default.

At which else attributes do you see hmi and main messages spamming?

2024-11-06 07:26 UTC, redahb commented
> @redahb please have a look at the [latest version](https://github.com/tspopp/AquaMQTT/releases/tag/v1.3.0) which adds temperature value filters using kalman. I am curious, if you still need these requested change since it dramatically reduces the amount of values emitted to the broker.
> 
> Cheers!

Hello @tspopp,

Sorry for the late reply but yes, for me I still need my changes after the kalman filters. I think we differ in opinion in what is interesting information. I am eternally grateful for the hardware and software you developed, so don't feel bad about it :).

I only really want to know 2 things from my boiler: Power draw and water temperature. Perhaps possibly inlet/outlet air temperature, but in reality that's it. Everything else, while it might be interesting for others, is 'noise' to me. I don't use it at all :)

2025-02-10 20:17 UTC, henrykuijpers commented
I finally had time to install the latest version. It still sends a lot of messages to the broker (and thus to Home Assistant as well):
<img width="888" alt="image" src="https://github.com/user-attachments/assets/f61a1027-6d2c-4192-ba95-5ab8cffc07d7" />

So indeed, I think these changes are still welcome. What is still open in these changes? Is there anything I can do?

2025-02-11 10:33 UTC, NickdeK commented
@henrykuijpers The [1.5.0](https://github.com/tspopp/AquaMQTT/releases/tag/v1.5.0) update includes the ability to [turn of the time update and stats messages](https://github.com/tspopp/AquaMQTT/pull/48/files). Set these values to false and the number of messages is significantly reduced.

2025-02-11 11:05 UTC, henrykuijpers commented
Thanks for that pointer, @NickdeK ! I completely missed this. I just turned them off and indeed, the flood is now gone. 

I'm not sure if disabling these updates by default is recommended, as @tspopp was specifically mentioning that it is very convenient for new users when they run into problems. 
I believe this PR aims to be a good solution between not publishing anything and publish everything all the time.

2025-02-11 11:52 UTC, NickdeK commented
Fair point @henrykuijpers My personal experience with this repo was pretty good without any mayor issues, so in my experience the debug messages where not needed, but I get that's just one user experience which might not represent everyone.

Still from a developer standpoint I would disable debug messages by default and include a readme rule somewhere to enable them when users are having issues so they can be included in bug reports. But that's for tspopp to decide, I'm perfectly fine with the PR being closed :)

2025-02-11 12:16 UTC, henrykuijpers commented
Probably it's best to put somewhere in the documentation "Warning! If your device is not in the supported devices list, be sure to enable debugging. When the boiler seems to run fine, debugging can be turned off by reflashing." 

I agree that it's better to turn it off by default.

2025-02-11 19:16 UTC, tspopp commented
Hey! Thanks for jumping in @NickdeK. Yes, in case your happy with the current functionality we can close this PR. If you still need this, I think it just needs a rebase and some minor changes I've requested back then.

We can disable the debug messages by default as well. I just need to add some note to the FAQ as proposed by @henrykuijpers :+1:

2025-02-17 20:23 UTC, closed without merging